# Generated by Django 4.2.15 on 2024-08-15 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HikeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('fam', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('otc', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, choices=[('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('1B', '1Б'), ('2B', '2Б'), ('3B', '3Б'), ('3B*', '3Б*')], max_length=3)),
                ('summer', models.CharField(blank=True, choices=[('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('1B', '1Б'), ('2B', '2Б'), ('3B', '3Б'), ('3B*', '3Б*')], max_length=3)),
                ('autumn', models.CharField(blank=True, choices=[('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('1B', '1Б'), ('2B', '2Б'), ('3B', '3Б'), ('3B*', '3Б*')], max_length=3)),
                ('spring', models.CharField(blank=True, choices=[('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('1B', '1Б'), ('2B', '2Б'), ('3B', '3Б'), ('3B*', '3Б*')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('other_titles', models.CharField(blank=True, max_length=128)),
                ('connect', models.CharField(blank=True, max_length=128)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новое'), ('pen', 'На рассмотрении'), ('acp', 'Принято'), ('rej', 'Отклонено')], default='new', max_length=3)),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mountpass.coords')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountpass.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountpass.hikeuser')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountpass.pereval')),
            ],
        ),
    ]
