# Generated by Django 4.2.15 on 2024-08-17 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mountpass', '0003_alter_hikeuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pereval',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mountpass.pereval'),
        ),
    ]
