# Generated by Django 4.2.15 on 2024-08-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountpass', '0004_alter_image_pereval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikeuser',
            name='fam',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hikeuser',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hikeuser',
            name='otc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hikeuser',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
