# Generated by Django 4.2.15 on 2024-08-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountpass', '0005_alter_hikeuser_fam_alter_hikeuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
