# Generated by Django 4.2.15 on 2024-08-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountpass', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='coords',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='coords',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
    ]
