# Generated by Django 4.2.15 on 2024-08-19 11:55

from django.db import migrations, models
import django.db.models.deletion
import mountpass.file_address


class Migration(migrations.Migration):

    dependencies = [
        ('mountpass', '0008_alter_coords_height_alter_coords_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=mountpass.file_address.take_image_file_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='pereval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mountpass.pereval'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Снимок'),
        ),
    ]
