# Generated by Django 4.2.15 on 2024-08-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountpass', '0011_alter_hikeuser_fam_alter_hikeuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
