# Generated by Django 5.2.4 on 2025-08-07 12:27

import mountpass.file_address
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mountpass", "0014_alter_pereval_add_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=mountpass.file_address.take_image_file_path,
                verbose_name="Picture",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Shot"
            ),
        ),
    ]
